version: '3.3'

services:
  meuproduto-backend:
    image: rderoci/meuproduto
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: meuproduto-backend
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    environment:
      - SPRING_PROFILES_ACTIVE=aws
    networks:
      - net-meuproduto
    ports:
      - 8080:8080

networks:
  net-meuproduto: